title: Railspeeder Documentation
description: Documentation hub for the Railspeeder project
theme: just-the-docs
url: https://slugbotics.com/railspeeder-doc/
logo: "/assets/images/Railspeeder.png"
color_scheme: dark
mermaid:
  version: "9.3.0"

